name: Validate PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Installing Packages
      run: yarn
      
    - name: Check CI works
      run: yarn start:tsc --dry-run